# Generated by Django 6.1.1 on 2026-09-03 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_marksheet'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('MIDTERM', 'Midterm'), ('FINAL', 'Final'), ('SUPPLEMENTARY', 'Supplementary'), ('IMPROVEMENT', 'Improvement')], max_length=20)),
                ('academic_session', models.CharField(max_length=30)),
                ('semester', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_forms', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='ExamFormSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_subjects', to='examinations.examform')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.result')),
            ],
        ),
    ]
