# Generated by Django 6.1.1 on 2026-09-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examform',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
